import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { Playfair_Display } from "next/font/google";
import "./globals.css";

import ClientFooterWrapper from "@/components/ClientFooterWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Laluxurygold",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfairDisplay.variable} ${inter.variable} antialiased pt-[64px]`}
      >
        
        {children}
        <ClientFooterWrapper />
      </body>
    </html>
  );
}
